package tela;

public enum AcaoTemplo {
	EVOLUCAO_NUVEM_GARFANHOTO, EVOLUCAO_MORTE_PRIMOGENITO, EVOLUCAO_CHUVA_PEDRA,
	EVOLUCAO_PROTECAO_NUVEM_GARFANHOTO, EVOLUCAO_PROTECAO_MORTE_PRIMOGENITO, EVOLUCAO_PROTECAO_CHUVA_PEDRA, PARAR;
}
